#nameOverride: injected
images:
  namespace: argoproj
  controller: workflow-controller
  ui: argoui
  executor: argoexec
  tag: injected

crdVersion: v1alpha1

init:
  # By default the installation will not set an explicit one, which will mean it uses `default` for the namespace the chart is
  # being deployed to.  In RBAC clusters, that will almost certainly fail.  See the NOTES: section of the readme for more info.
  serviceAccount: ""

controller:
  # podAnnotations is an optional map of annotations to be applied to the controller Pods
  podAnnotations: {}
  serviceAccount: argo
  name: workflow-controller
  workflowNamespaces:
    - default
  instanceID:
    # `instanceID.enabled` configures the controller to filter workflow submissions
    # to only those which have a matching instanceID attribute.
    enabled: false
    # NOTE: If `instanceID.enabled` is set to `true` then either `instanceID.userReleaseName`
    # or `instanceID.explicitID` must be defined.
    # useReleaseName: true
    # explicitID: unique-argo-controller-identifier
  logging:
    level: info
    globallevel: "0"

ui:
  # optional map of annotations to be applied to the ui Pods
  podAnnotations: {}
  name: ui
  serviceType: ClusterIP
  servicePort: 80
  serviceAccount: argo-ui
  # Annotations to be applied to the UI Service
  serviceAnnotations: {}
  
  ## Ingress configuration.
  ## ref: https://kubernetes.io/docs/user-guide/ingress/
  ##
  ingress:
    enabled: injected

    ## Annotations to be added to the web ingress.
    ##
    # annotations:
    #   kubernetes.io/ingress.class: nginx
    #   kubernetes.io/tls-acme: "true"

    ## Hostnames.
    ## Must be provided if Ingress is enabled.
    ##
    hosts: injected
    #  - argo.mylocalkube

    ## TLS configuration.
    ## Secrets must be manually created in the namespace.
    ##
    # tls:
    #   - secretName: argo-ui-tls
    #     hosts:
    #       - argo.domain.com

# Influences the creation of the ConfigMap for the workflow-controller itself.
useDefaultArtifactRepo: true
useStaticCredentials: true
artifactRepository:
  s3:
    # Note the `key` attribute is not the actual secret, it's the PATH to
    # the contents in the associated secret, as defined by the `name` attribute.
    accessKeySecret:
      name: injected
      key: accesskey
    secretKeySecret:
      name: injected
      key: secretkey
    insecure: true
    bucket: injected
    endpoint: injected

# NOTE: These are setting attributes for the `minio` optional dependency
minio:
  # If set to true then chart installs minio and generate according artifactRepository section in workflow controller config map
  install: false
  defaultBucket:
    enabled: true
    name: injected
  persistence:
    enabled: injected  
  ingress:
    enabled: injected  
    hosts: 
      - chart-example.local

