#
#   Copyright 2019 Ericsson AB.
#   For a full list of individual contributors, please see the commit history.
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.
#
# Ports used for communicate between services in Docker Host.
export EIFFEL_MONGODB_APPLICATION_PORT=${EIFFEL_MONGODB_INTERNAL_PORT}
export EIFFEL_RABBITMQ_AMQP_APPLICATION_PORT=${EIFFEL_RABBITMQ_AMQP_INTERNAL_PORT}
export EIFFEL_RABBITMQ_WEB_APPLICATION_PORT=${EIFFEL_RABBITMQ_WEB_INTERNAL_PORT}
export EIFFEL_DUMMY_ER_APPLICATION_PORT=${EIFFEL_DUMMY_ER_INTERNAL_PORT}
export EIFFEL_ER_APPLICATION_PORT=${EIFFEL_ER_INTERNAL_PORT}
export EIFFEL_JENKINS_FEM_APPLICATION_PORT=${EIFFEL_JENKINS_FEM_INTERNAL_PORT}
export EIFFEL_JENKINS_APPLICATION_PORT=${EIFFEL_JENKINS_INTERNAL_PORT}
export EIFFEL_NEXUS_APPLICATION_PORT=${EIFFEL_NEXUS_INTERNAL_PORT}
export EIFFEL_REMREM_GENERATE_APPLICATION_PORT=${EIFFEL_REMREM_GENERATE_INTERNAL_PORT}
export EIFFEL_REMREM_PUBLISH_APPLICATION_PORT=${EIFFEL_REMREM_PUBLISH_INTERNAL_PORT}
export EIFFEL_EI_BACKEND_ARTIFACT_APPLICATION_PORT=${EIFFEL_EI_BACKEND_ARTIFACT_INTERNAL_PORT}
export EIFFEL_EI_BACKEND_SOURCECHANGE_APPLICATION_PORT=${EIFFEL_EI_BACKEND_SOURCECHANGE_INTERNAL_PORT}
export EIFFEL_EI_BACKEND_TESTEXECUTION_APPLICATION_PORT=${EIFFEL_EI_BACKEND_TESTEXECUTION_INTERNAL_PORT}
export EIFFEL_EI_BACKEND_ALLEVENTS_APPLICATION_PORT=${EIFFEL_EI_BACKEND_ALLEVENTS_INTERNAL_PORT}
export EIFFEL_EI_FRONTEND_APPLICATION_PORT=${EIFFEL_EI_FRONTEND_INTERNAL_PORT}
export EIFFEL_EI_FRONTEND_EXTERNAL_APPLICATION_PORT=${EIFFEL_EI_FRONTEND_EXTERNAL_PORT}

# When executed in Docker, it should be DockerHost IP address instead of EI-Frontend container hostname.
export EIFFEL_EI_FRONTEND=${HOST}
