name: easy2use-ci
 
on:
  push:
  pull_request:
    branches: [ issue-4 ]
 
jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3

      - name: Kubernetes Version
        run: |
              kubectl version

      - name: Install Easy2Use on cluster
        run: |
              kubectl create ns ci-eiffel
              ./easy2use start -t Kubernetes -d cluster.local -e ./bundles -n ci-eiffel Eiffel -y
              sleep 10

      - name: List the Eiffel pods
        run: |
              kubectl get pods -n ci-eiffel

      - name: Remove Easy2Use from cluster
        run: |
              ./easy2use remove -t Kubernetes -d cluster.local -e ./bundles -n ci-eiffel Eiffel -y
              kubectl delete ns ci-eiffel
